baseURL = "https://www.rajwadkar.net/"
title = "Rambles of a Technologist in Business" 
theme = "hugo-nederburg-theme-static"
languageCode = "en-gb"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  slogan = "WHEN there is a WILL, there is a WAY"
  description = "Rambles of a Technologist in Business" # meta description
  author = "Mayuresh Rajwadkar"
  authorLink = "https://www.rajwadkar.net/"
  bio = [
  "I am a semiconductor and IT professional working to finesse my life and business skills"
  ]
  copyright = [
    "&copy;2018 Mayuresh Rajwadkar"
  ]
#  "I am a semiconductor and IT professional newly minted with a MBA in entreprenuership from Babson College. I have worked for about twenty years primararily in the Semiconductor Industry as a design and development Engineer. I also have experience with Linux and the open source software industry and am very apt with Linux infrastructures and deployment.<p> This website is under construction"

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "m.m.rajwadkar+www@ieee.org"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Resume"
  url = "about/resume.pdf"
  weight = 2

  [[menu.main]]
  name = "Contact Me"
  url = "contact/"
  weight = 3

  [params.social]
  facebook       = "https://www.facebook.com/mayuresh.rajwadkar"
#  googleplus    = "full profile url in googleplus"
   email         = "m.m.rajwadkar+www@ieee.org"
  twitter        = "https://www.twitter.com/MayurRajwadkar"
  linkedin       = "https://www.linkedin.com/in/ememare"
  amazon         = "http://a.co/5qgWFXQ"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
#  github        = "full profile url in github"
#  youtube       = "full profile url in youtube" 
   rss           = true

 [params.writers]
    [params.writers."Mayuresh Rajwadkar"]
    link = "https://ww.rajwadkar.net/"
    email = "m.m.rajwadkar+www@ieee.org"
    bio = [
      "Mayuresh is a blach black "
    ]
